spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.tomcat.max-threads=40
server.tomcat.min-spare-threads=20
spring.datasource.hikari.maximum-pool-size=40
spring.datasource.hikari.minimum-idle=20
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.org.springframework=WARN